version: '3.5'

services:
  db_postgresql:
    image: postgres:16-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
    - POSTGRES_USER=dns-test-dev-usr
    - POSTGRES_PASSWORD=123456789
    - POSTGRES_DB=dns-test-dev
    expose: 
      - 5432
    networks:
      - app_network


  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "test-app"
    ports:
      - "34000:34000"
    depends_on:
      - db_postgresql
    env_file:
      - .env
    networks:
      - app_network




volumes:
  postgres_data:

networks:
  app_network:
