"""deprecated SaleProduct

Revision ID: 110320f0d6a1
Revises: a1b86d4af9ce
Create Date: 2024-10-23 06:20:01.196643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '110320f0d6a1'
down_revision: Union[str, None] = 'a1b86d4af9ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SaleProduct')
    op.add_column('sale', sa.Column('operation_uid', sa.Integer(), nullable=False))
    op.add_column('sale', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('sale', sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('sale', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sale', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale', type_='foreignkey')
    op.drop_column('sale', 'product_id')
    op.drop_column('sale', 'total_price')
    op.drop_column('sale', 'quantity')
    op.drop_column('sale', 'operation_uid')
    op.create_table('SaleProduct',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sale_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='SaleProduct_product_id_fkey'),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], name='SaleProduct_sale_id_fkey')
    )
    # ### end Alembic commands ###
