"""DECIMAL precision 10 to 32

Revision ID: ffaa2a0898c4
Revises: c2b5069e7b61
Create Date: 2024-10-27 23:05:17.739665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffaa2a0898c4'
down_revision: Union[str, None] = 'c2b5069e7b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=32, scale=2),
               existing_nullable=False)
    op.alter_column('sale', 'total_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=32, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale', 'total_price',
               existing_type=sa.DECIMAL(precision=32, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('product', 'price',
               existing_type=sa.DECIMAL(precision=32, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
