"""refactore id columns

Revision ID: 6e20965da271
Revises: 110320f0d6a1
Create Date: 2024-10-23 18:09:38.217065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e20965da271'
down_revision: Union[str, None] = '110320f0d6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('city', 'id', nullable=False, new_column_name='city_id')
    op.alter_column('city', 'name', nullable=False, new_column_name='city_name')
    op.alter_column('product', 'id', nullable=False, new_column_name='product_id')
    op.alter_column('product', 'name', nullable=False, new_column_name='product_name')
    op.alter_column('sale', 'id', nullable=False, new_column_name='sale_id')
    op.alter_column('store', 'id', nullable=False, new_column_name='store_id')
    op.alter_column('store', 'name', nullable=False, new_column_name='store_name')

    # op.add_column('city', sa.Column('city_id', sa.Integer(), autoincrement=True, nullable=False))
    # op.add_column('city', sa.Column('city_name', sa.String(), nullable=False))
    # op.drop_column('city', 'id')
    # op.drop_column('city', 'name')
    # op.add_column('product', sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False))
    # op.add_column('product', sa.Column('product_name', sa.String(), nullable=False))
    # op.drop_column('product', 'id')
    # op.drop_column('product', 'name')
    # op.add_column('sale', sa.Column('sale_id', sa.Integer(), autoincrement=True, nullable=False))
    # op.drop_constraint('sale_product_id_fkey', 'sale', type_='foreignkey')
    # op.drop_constraint('sale_store_id_fkey', 'sale', type_='foreignkey')
    # op.create_foreign_key(None, 'sale', 'product', ['product_id'], ['product_id'])
    # op.create_foreign_key(None, 'sale', 'store', ['store_id'], ['store_id'])
    # op.drop_column('sale', 'id')
    # op.add_column('store', sa.Column('store_id', sa.Integer(), autoincrement=True, nullable=False))
    # op.add_column('store', sa.Column('store_name', sa.String(), nullable=False))
    # op.drop_constraint('store_city_id_fkey', 'store', type_='foreignkey')
    # op.create_foreign_key(None, 'store', 'city', ['city_id'], ['city_id'])
    # op.drop_column('store', 'id')
    # op.drop_column('store', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('city', 'city_id', nullable=False, new_column_name='id')
    op.alter_column('city', 'city_name', nullable=False, new_column_name='name')
    op.alter_column('product', 'product_id', nullable=False, new_column_name='id')
    op.alter_column('product', 'product_name', nullable=False, new_column_name='name')
    op.alter_column('sale', 'sale_id', nullable=False, new_column_name='id')
    op.alter_column('store', 'store_id', nullable=False, new_column_name='id')
    op.alter_column('store', 'store_name', nullable=False, new_column_name='name')

    # op.add_column('store', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # op.add_column('store', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('store_id_seq'::regclass)"), autoincrement=True, nullable=False))
    # op.drop_constraint(None, 'store', type_='foreignkey')
    # op.create_foreign_key('store_city_id_fkey', 'store', 'city', ['city_id'], ['id'])
    # op.drop_column('store', 'store_name')
    # op.drop_column('store', 'store_id')
    # op.add_column('sale', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # op.drop_constraint(None, 'sale', type_='foreignkey')
    # op.drop_constraint(None, 'sale', type_='foreignkey')
    # op.create_foreign_key('sale_store_id_fkey', 'sale', 'store', ['store_id'], ['id'])
    # op.create_foreign_key('sale_product_id_fkey', 'sale', 'product', ['product_id'], ['id'])
    # op.drop_column('sale', 'sale_id')
    # op.add_column('product', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # op.add_column('product', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('product_id_seq'::regclass)"), autoincrement=True, nullable=False))
    # op.drop_column('product', 'product_name')
    # op.drop_column('product', 'product_id')
    # op.add_column('city', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # op.add_column('city', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('city_id_seq'::regclass)"), autoincrement=True, nullable=False))
    # op.drop_column('city', 'city_name')
    # op.drop_column('city', 'city_id')
    # ### end Alembic commands ###
