"""add_unique_constant_city_name

Revision ID: bbd3d32693a4
Revises: 4ddee061b580
Create Date: 2024-10-27 12:41:11.468933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd3d32693a4'
down_revision: Union[str, None] = '4ddee061b580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'city', ['city_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'city', type_='unique')
    # ### end Alembic commands ###
