"""add_unique_constant_sale

Revision ID: c2b5069e7b61
Revises: 875770926f62
Create Date: 2024-10-27 12:50:45.982423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2b5069e7b61'
down_revision: Union[str, None] = '875770926f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sale', ['operation_uid', 'sale_date', 'quantity', 'total_price', 'store_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale', type_='unique')
    # ### end Alembic commands ###
