INSERT INTO store (store_name,city_id)
VALUES
  ('Morbi Institute',45),
  ('Orci LLC',3),
  ('Vestibulum Nec Euismod Associates',7),
  ('Commodo Hendrerit Donec Company',18),
  ('Aliquam Vulputate Associates',2),
  ('Nascetur LLC',19),
  ('Accumsan Interdum Inc.',10),
  ('Mauris A Corp.',40),
  ('Aliquam Eu Accumsan Institute',4),
  ('Vestibulum Ante Industries',32),
  ('Risus Morbi Metus Industries',19),
  ('Urna Ut Ltd',37),
  ('Morbi Metus Associates',33),
  ('Arcu Iaculis LLC',8),
  ('Ornare In Faucibus Industries',14),
  ('In Incorporated',45),
  ('Fusce Fermentum Incorporated',19),
  ('Mauris Ut LLC',41),
  ('Facilisis PC',19),
  ('Purus Duis Elementum Limited',37),
  ('Non Hendrerit Limited',15),
  ('Penatibus Et Industries',30),
  ('Integer Aliquam LLC',20),
  ('Integer Urna Corporation',12),
  ('Eget Magna Suspendisse PC',27),
  ('Consequat Nec Mollis Corp.',22),
  ('Malesuada Fringilla LLP',41),
  ('Sagittis Corp.',48),
  ('Tellus Phasellus LLC',19),
  ('Massa Vestibulum Corporation',49),
  ('Libero Est Associates',20),
  ('Laoreet Institute',37),
  ('At Auctor Industries',30),
  ('Eget Incorporated',34),
  ('In Tempus Associates',1),
  ('Varius Nam Limited',47),
  ('Ut Sem Nulla Foundation',20),
  ('Nec Limited',18),
  ('Varius Ultrices Associates',11),
  ('Vehicula LLC',25),
  ('Ut Nisi PC',29),
  ('Donec Non Justo LLC',30),
  ('Eros Non LLP',33),
  ('Ipsum Dolor Consulting',2),
  ('Magna Nec Limited',36),
  ('Amet Diam PC',17),
  ('Nunc Ac Sem Consulting',38),
  ('Mollis Integer PC',33),
  ('Feugiat Inc.',7),
  ('Vehicula Aliquet Company',26),
  ('Erat Nonummy LLC',31),
  ('Justo Proin Limited',24),
  ('Mauris Eu Institute',22),
  ('Magna Sed Inc.',46),
  ('Eleifend Nunc Corporation',42),
  ('Facilisis Lorem LLC',5),
  ('Amet Institute',15),
  ('Adipiscing Institute',11),
  ('Quam Curabitur Foundation',44),
  ('Eu Elit LLP',44),
  ('Sem Vitae Limited',43),
  ('Suspendisse Consulting',37),
  ('Cras Sed Company',9),
  ('Non Inc.',43),
  ('Non Enim Ltd',11),
  ('Nullam Suscipit Est Company',31),
  ('Fusce Corporation',23),
  ('Lorem Eget LLP',39),
  ('Adipiscing Corporation',39),
  ('Eget Massa Institute',6),
  ('Suscipit Institute',37),
  ('Pede Praesent Corporation',43),
  ('In Hendrerit PC',14),
  ('Facilisi PC',10),
  ('Ante Dictum Inc.',13),
  ('Dictum Eleifend LLP',5),
  ('Consequat Nec Mollis Institute',32),
  ('Vel Corp.',9),
  ('Donec Est Limited',3),
  ('Vulputate Velit Associates',36),
  ('Enim Etiam Corp.',48),
  ('Magna Sed Institute',22),
  ('Ornare Lectus Corp.',47),
  ('Tincidunt Congue Limited',48),
  ('Nisi Magna Corporation',49),
  ('Eu Erat LLP',28),
  ('Nam Ac Inc.',21),
  ('Urna Suscipit Nonummy Ltd',19),
  ('Nisi Cum Sociis Associates',1),
  ('Purus Duis Associates',41),
  ('Dolor Sit LLP',5),
  ('Id Magna Inc.',21),
  ('Dolor Sit LLC',17),
  ('Nunc Mauris Incorporated',6),
  ('Morbi Tristique Incorporated',33),
  ('Enim Mi Tempor Corp.',36),
  ('Sapien Aenean Corporation',16),
  ('Libero Institute',4),
  ('Cursus Non Incorporated',13),
  ('Ornare Elit Ltd',50),
  ('Pellentesque Massa Consulting',11),
  ('Ac Libero Industries',24),
  ('Convallis Limited',9),
  ('Pellentesque Eget Industries',34),
  ('Nunc Risus Incorporated',15),
  ('Magna Tellus PC',11),
  ('Lectus Convallis LLC',19),
  ('Ultrices Vivamus Rhoncus Ltd',40),
  ('Venenatis Vel Faucibus Incorporated',45),
  ('Cras Inc.',1),
  ('Nunc Nulla Ltd',46),
  ('Magna A Neque Incorporated',26),
  ('Amet Foundation',5),
  ('Donec Luctus Corp.',31),
  ('Dolor Inc.',51),
  ('Enim Etiam Imperdiet Institute',3),
  ('Fringilla Porttitor Vulputate Foundation',35),
  ('Purus Accumsan Corp.',29),
  ('At Auctor PC',15),
  ('Ligula Associates',19),
  ('Curabitur Sed Consulting',34),
  ('Nonummy Corporation',16),
  ('Vitae Aliquet LLC',25),
  ('Ligula Consulting',31),
  ('Magna Cras Corporation',39),
  ('Ut Associates',36),
  ('Maecenas Iaculis Aliquet Institute',27),
  ('Sed Eu Corp.',19),
  ('Massa Vestibulum Accumsan Incorporated',16),
  ('Dictum Sapien LLC',34),
  ('Convallis Ligula Donec Foundation',44),
  ('Lectus Ante Institute',19),
  ('Vitae Risus Limited',15),
  ('Conubia Nostra Incorporated',30),
  ('Curae Phasellus LLP',33),
  ('Gravida Institute',21),
  ('Mauris Non Inc.',6),
  ('Purus Accumsan Institute',15),
  ('Est Mauris Rhoncus Corp.',40),
  ('Rhoncus Associates',29),
  ('Enim Sed LLC',20),
  ('Mi Felis Adipiscing LLC',46),
  ('Conubia Nostra Consulting',25),
  ('Duis Corp.',48),
  ('Molestie Sed LLC',28),
  ('Nunc Ac Mattis Institute',12),
  ('Nisi Nibh Associates',15),
  ('Ligula Tortor Incorporated',27),
  ('Vitae Ltd',34),
  ('Fusce Fermentum Inc.',1),
  ('metus. In',34),
  ('inceptos hymenaeos.',20),
  ('velit. Aliquam',40),
  ('ligula. Nullam',28),
  ('Phasellus fermentum',16),
  ('neque sed',2),
  ('justo sit',1),
  ('tincidunt pede',4),
  ('ridiculus mus.',4),
  ('orci, adipiscing',43),
  ('a, enim.',7),
  ('fringilla est.',25),
  ('rhoncus. Proin',48),
  ('magna. Lorem',36),
  ('sagittis. Duis',21),
  ('lorem, eget',28),
  ('elit, pellentesque',5),
  ('vitae odio',24),
  ('lobortis quam',40),
  ('tortor nibh',48),
  ('netus et',46),
  ('risus. Donec',17),
  ('vel, venenatis',31),
  ('nonummy ultricies',45),
  ('elit elit',8),
  ('diam luctus',15),
  ('semper. Nam',44),
  ('imperdiet nec,',9),
  ('montes, nascetur',48),
  ('tincidunt dui',10),
  ('sem mollis',11),
  ('feugiat. Sed',11),
  ('pulvinar arcu',21),
  ('consequat enim',30),
  ('rhoncus. Nullam',27),
  ('Fusce aliquam,',10),
  ('vel, mauris.',13),
  ('eu tellus',6),
  ('mi lorem,',27),
  ('metus. In',34),
  ('vel lectus.',30),
  ('turpis egestas.',47),
  ('odio tristique',22),
  ('facilisis non,',2),
  ('vitae, erat.',19),
  ('urna et',4),
  ('consequat auctor,',39),
  ('enim, condimentum',22),
  ('nisi dictum',43),
  ('ac urna.',45),
  ('consectetuer mauris',24),
  ('ornare lectus',9),
  ('sodales. Mauris',23),
  ('velit. Quisque',19),
  ('mi eleifend',36),
  ('tellus eu',28),
  ('lectus justo',7),
  ('feugiat tellus',48),
  ('cursus. Integer',37),
  ('enim non',19),
  ('consectetuer, cursus',3),
  ('porttitor scelerisque',42),
  ('ipsum. Suspendisse',51),
  ('nibh vulputate',15),
  ('ullamcorper magna.',51),
  ('ac, feugiat',50),
  ('leo elementum',28),
  ('Quisque purus',38),
  ('Nunc mauris',5),
  ('est, vitae',40),
  ('pede. Suspendisse',5),
  ('est, congue',4),
  ('In faucibus.',39),
  ('Maecenas mi',38),
  ('vulputate eu,',40),
  ('quis accumsan',47),
  ('rutrum urna,',48),
  ('pede, malesuada',19),
  ('enim non',17),
  ('accumsan interdum',36),
  ('gravida. Aliquam',41),
  ('luctus vulputate,',44),
  ('libero. Morbi',33),
  ('nisi sem',20),
  ('Nam ligula',21),
  ('eget odio.',11),
  ('ut, molestie',25),
  ('scelerisque dui.',30),
  ('magnis dis',3),
  ('urna justo',38),
  ('ultrices sit',10),
  ('ipsum nunc',12),
  ('facilisis eget,',20),
  ('Duis mi',22),
  ('Donec est',51),
  ('Cras dictum',39),
  ('sem elit,',27),
  ('sapien. Nunc',26),
  ('Donec porttitor',45),
  ('amet, risus.',39),
  ('amet, consectetuer',39),
  ('lacus. Aliquam',20),
  ('et ipsum',7),
  ('mi lacinia',47),
  ('id sapien.',23),
  ('velit eu',9),
  ('molestie pharetra',24),
  ('et ultrices',7),
  ('sed tortor.',31),
  ('ornare placerat,',31),
  ('nisl. Quisque',17),
  ('sit amet',21),
  ('adipiscing fringilla,',51),
  ('in, cursus',47),
  ('tortor. Nunc',3),
  ('Etiam bibendum',45),
  ('risus. Donec',31),
  ('elit fermentum',15),
  ('arcu. Sed',35),
  ('sed dolor.',30),
  ('ultricies ligula.',13),
  ('eu dolor',9),
  ('Pellentesque ultricies',13),
  ('semper egestas,',51),
  ('porttitor tellus',48),
  ('id enim.',13),
  ('tempor lorem,',45),
  ('urna suscipit',21),
  ('pede. Cum',24),
  ('sociis natoque',28),
  ('mi felis,',50),
  ('lacinia vitae,',8),
  ('Donec nibh',12),
  ('egestas a,',31),
  ('magnis dis',14),
  ('Nullam enim.',17),
  ('mollis. Integer',2),
  ('dui quis',24),
  ('augue eu',8),
  ('sem, vitae',34),
  ('faucibus. Morbi',29),
  ('volutpat. Nulla',48),
  ('posuere vulputate,',28),
  ('auctor non,',14),
  ('massa. Mauris',19),
  ('arcu et',31),
  ('diam at',18),
  ('enim consequat',15),
  ('odio. Nam',39),
  ('eu neque',49),
  ('odio, auctor',3),
  ('Donec egestas.',21),
  ('Curabitur ut',33),
  ('rutrum non,',13),
  ('amet ultricies',2),
  ('sem semper',50),
  ('vitae mauris',32),
  ('ut, pellentesque',40),
  ('in aliquet',5),
  ('non, cursus',32),
  ('commodo hendrerit.',42),
  ('felis orci,',25),
  ('odio, auctor',24),
  ('vitae nibh.',3),
  ('ut eros',9),
  ('arcu. Vivamus',51),
  ('Fusce mi',6),
  ('urna convallis',46),
  ('a feugiat',39),
  ('vulputate mauris',32);
